#!/usr/bin/env bash

# Collect on-CPU stack samples with perf and generate flame graphs.
#
# This script supports two common workflows:
# 1) profile an existing process by PID
# 2) launch a command, wait for it to start running, then profile it
#
# It can also run in system-wide mode when no target PID or command is given.
# In that case perf samples all CPUs instead of a specific process.
#
# High-level flow:
# 1) parse user options
# 2) verify passwordless sudo is available because perf and package installs use sudo
# 3) print several kernel perf-related sysctl values for quick environment inspection
# 4) install required tools on demand: eu-stack, perf, FlameGraph scripts
# 5) optionally wait before recording starts
# 6) resolve the profiling target:
#    - numeric argument      -> treat as PID
#    - steam                -> ask user for the game PID
#    - anything else        -> launch it as a detached background process
# 7) optionally install debug symbol packages for the target process to improve stack quality
# 8) record perf samples for a fixed duration
# 9) convert perf output into folded stacks and then SVG flame graphs
# 10) when profiling a multi-threaded process, also split samples by TID and generate
#     one flame graph per thread
#
# Implementation notes:
# - perf record collects sampled call stacks into /tmp/perf.data
# - perf script converts the binary perf.data file into a text stream
# - stackcollapse-perf.pl converts perf script output into folded stack format
# - flamegraph.pl renders the folded stacks into an interactive SVG flame graph
# - per-thread flame graphs are generated by splitting perf script records by TID first

set -o pipefail

NAME_PREFIX=
WAIT_SECONDS=0 # Delay before perf recording starts.
RECORD_SECONDS=5 # perf recording duration in seconds.
RECORD_FREQ=1000 # perf sampling frequency in Hz.
UNWIND_METHOD=dwarf # dwarf or fp (frame pointer)
INSTALL_DEBUG_SYMBOL=true
DEBUGINFOD_URLS="https://debuginfod.ubuntu.com"

# These are filled later after the target is resolved.
unset PID COMM

# Parse leading script options.
# Parsing stops at the first non-option token, which becomes either:
# - a PID
# - the special keyword steam
# - or the command to launch and profile
while (( $# )); do
    case $1 in
        -name=*) NAME_PREFIX=${1#-name=} ;;
        -wait=*) WAIT_SECONDS=${1#-wait=} ;;
        -record=*) RECORD_SECONDS=${1#-record=} ;;
        -freq=*) RECORD_FREQ=${1#-freq=} ;;
        -unwind=*) UNWIND_METHOD=${1#-unwind=} ;;
        -dbgsym=*) INSTALL_DEBUG_SYMBOL=${1#-dbgsym=} ;;
        *) break ;;
    esac
    shift
 done

# sudo is required for perf record, perf script access, package installation, and some
# temporary file management. The script intentionally requires passwordless sudo so the
# workflow stays non-interactive once recording starts.
if ! sudo -n true 2>/dev/null; then
    echo "Error: NOPASSWD is NOT enabled for $(id -un)"
    echo "Aborting"
    exit 1
fi

# Print a few kernel knobs that commonly affect perf usability and symbol visibility.
# This is only informational but helps explain unexpected missing stacks or permission
# failures on new systems.
echo "=== sysctl knobs (runtime kernel params) ==="
echo "/proc/sys/kernel/perf_event_paranoid => $(cat /proc/sys/kernel/perf_event_paranoid)"
echo "/proc/sys/kernel/kptr_restrict => $(cat /proc/sys/kernel/kptr_restrict)"
echo "/proc/sys/kernel/perf_event_max_sample_rate => $(cat /proc/sys/kernel/perf_event_max_sample_rate)"
echo

# Install required tools on demand.
# - eu-stack: quick stack utility from elfutils, useful in the profiling workflow
# - perf: kernel/userspace sampler
# - flamegraph.pl + stackcollapse-perf.pl: render SVG flame graphs from perf samples
[[ -z $(which eu-stack) ]] && sudo apt install -y elfutils >/dev/null 2>&1
[[ -z $(which perf) ]] && sudo apt install -y linux-tools-$(uname -r) linux-cloud-tools-$(uname -r) linux-tools-generic linux-cloud-tools-generic
[[ -z $(which flamegraph.pl) ]] && git clone https://github.com/brendangregg/FlameGraph.git /tmp/fg && sudo cp -f /tmp/fg/*.pl /usr/local/bin/

# Remove previous output from earlier runs so the new result is easier to inspect.
sudo rm -rf /tmp/perf.data $HOME/perf-system-wide.svg $HOME/perf.svg.d/

# Optional delay before recording starts.
if (( WAIT_SECONDS > 0 )); then
    echo "Wait $WAIT_SECONDS seconds before recording"
    sleep $WAIT_SECONDS
fi

# Resolve the target process or launch a new command.
if [[ ! -z $1 ]]; then
    if [[ $1 =~ ^[0-9]+$ ]]; then
        # Numeric argument: profile an already-running PID.
        PID=$1
    elif [[ $1 == steam && ! -z $(pidof steam) ]]; then
        # Steam helper mode: show the Steam tree, then let the user manually choose the
        # game PID because Steam itself is usually not the real workload we want.
        pstree -aspT $(pidof steam)
        read -p "Input steam game PID: " PID
    else
        # Otherwise treat the remaining arguments as a command to launch.
        # The command runs detached in the background and its stdout/stderr go to a log.
        "$@" >$HOME/profiling-logs.txt 2>&1 &
        PID=$!
        echo "Detached process $PID"
    fi

    # Resolve the command name of the target process.
    # This is later used for diagnostics and the debug-symbol installation marker file.
    COMM=$(cat /proc/$PID/comm 2>/dev/null)
    [[ -z $COMM ]] && COMM=unknown

    # Optionally install debug symbol packages for the target process.
    # Implementation details:
    # - find-dbgsym-packages inspects the process mappings and prints matching dbgsym pkgs
    # - each package is installed with apt
    # - a per-comm marker file in /tmp avoids re-installing on every run
    if [[ $INSTALL_DEBUG_SYMBOL == true ]]; then
        if [[ ! -f /tmp/$(cat /proc/$PID/comm)-dbgsym-installed && ! -z $(which find-dbgsym-packages) ]]; then
            echo "Installing debug symbols for process $PID..."
            find-dbgsym-packages $PID 2>/dev/null | tr ' ' '\n' | while read -r pkg; do
                sudo apt install -y $pkg
            done
            touch /tmp/$(cat /proc/$PID/comm)-dbgsym-installed
        fi
    fi

    # Show quick process context before recording:
    # - pstree: parent/child relation and arguments
    # - pidstat -t: per-thread statistics snapshot
    pstree -aspT $PID
    pidstat -t -p $PID
fi

# Start sampling.
# - system-wide mode: perf record -a samples all CPUs
# - per-process mode: perf record --pid samples only the target process
# Samples are written to /tmp/perf.data.
echo "Recording for $RECORD_SECONDS seconds ..."
sudo perf record $([[ -z $PID ]] && echo "-a" || echo "--pid=$PID") --freq=$RECORD_FREQ -g --call-graph $UNWIND_METHOD -o /tmp/perf.data -- sleep $RECORD_SECONDS

# Post-process perf.data into flame graphs.
if [[ -f /tmp/perf.data ]]; then
    # Convert binary perf.data into text records.
    sudo perf script -i /tmp/perf.data >/tmp/perf.txt
    chmod 666 /tmp/perf.txt

    if [[ -z $PID ]]; then
        # System-wide mode: generate one combined SVG for the whole machine.
        cat /tmp/perf.txt | stackcollapse-perf.pl 2>/dev/null | flamegraph.pl >$HOME/perf-system-wide.svg && echo "Generated $HOME/perf-system-wide.svg"
    else
        # Per-process mode: always generate one SVG that combines all threads.
        mkdir -p $HOME/perf.svg.d/
        cat /tmp/perf.txt | stackcollapse-perf.pl 2>/dev/null | flamegraph.pl >$HOME/perf.svg.d/perf-all-threads.svg && echo "Generated $HOME/perf.svg.d/perf-all-threads.svg"

        # If the process has multiple threads, also generate one SVG per thread.
        #
        # Implementation details of the splitting step:
        # - perf script output is organized as blank-line-separated records
        # - awk reads each record with RS=""
        # - the first line of each record contains a token like PID/TID
        # - that TID is extracted and used to append the whole record into
        #   /tmp/perf-tid<TID>.txt
        # - each per-TID text file is then collapsed and rendered independently
        if [[ -d /proc/$PID/task ]] && (( $(ls /proc/$PID/task 2>/dev/null | wc -l) > 1 )); then
            sudo rm -rf /tmp/perf-tid*
            awk '
                BEGIN { RS=""; ORS="" }
                {
                    split($0, lines, "\n")
                    split(lines[1], w, /[ \t]+/)
                    tid=""
                    for (i = 1; i <= length(w); i++) {
                        if (match(w[i], /^[0-9]+\/[0-9]+$/)) {
                            split(w[i], a, "/")
                            tid=a[2]
                            break
                        }
                    }
                    if (tid == "") tid="unknown"
                    file="/tmp/perf-tid" tid ".txt"
                    print $0 "\n\n" >> file
                }
            ' /tmp/perf.txt

            # Count how many unique per-thread files were produced. Only generate per-thread
            # SVGs when more than one thread was actually found in perf output.
            tid_count=$(ls /tmp/perf-tid*.txt 2>/dev/null | sed -n 's|.*/perf-tid\([0-9]\+\)\.txt$|\1|p' | sort -u | wc -l)
            if (( tid_count > 1 )); then
                for file in /tmp/perf-tid*.txt; do
                    [[ -f $file ]] || continue
                    tid=${file#/tmp/perf-tid}
                    tid=${tid%.txt}
                    [[ $tid == unknown ]] && continue
                    cat $file | stackcollapse-perf.pl 2>/dev/null | flamegraph.pl >$HOME/perf.svg.d/tid$tid.svg
                    echo "Generated $HOME/perf.svg.d/tid$tid.svg"
                done
            fi
        fi

        # Optional final rename so multiple profiling runs can coexist under different names.
        if [[ ! -z $NAME_PREFIX ]]; then
            sudo mv -f $HOME/perf.svg.d $HOME/$NAME_PREFIX.perf.svg.d
            echo "Renamed output dir to $HOME/$NAME_PREFIX.perf.svg.d"
        fi
    fi
fi
