#!/usr/bin/env bash
# Called from perf-record-and-postprocess.sh in the same dir. Do not run directly.
# Expects: PID, COMM; /tmp/perf.txt must exist.

set -o pipefail

# Guardian: required variables and inputs.
: "${PID:?generate-perthread-flamegraph.sh: PID must be set (call only from perf-record-and-postprocess.sh when PID is set)}"
: "${COMM:?generate-perthread-flamegraph.sh: COMM must be set}"
[[ "$PID" =~ ^[0-9]+$ ]] || { echo "generate-perthread-flamegraph.sh: PID must be a positive integer" >&2; exit 1; }
[[ -f /tmp/perf.txt ]] || { echo "generate-perthread-flamegraph.sh: /tmp/perf.txt must exist (run perf-record-and-postprocess.sh first)" >&2; exit 1; }

# If the process has multiple threads, also generate one SVG per thread.
if [[ -d /proc/$PID/task ]] && (( $(ls /proc/$PID/task 2>/dev/null | wc -l) > 1 )); then
    echo "$COMM ($PID) has $(ls /proc/$PID/task 2>/dev/null | wc -l) threads"
    sudo rm -rf /tmp/perf_tid*
    # Split perf script output by TID. Process line-by-line so we don't rely on blank lines
    # between samples; each line is appended to the file for the TID from the last seen
    # header line (a line containing pid/tid).
    awk '
        BEGIN { cur_tid = "" }
        /[0-9]+\/[0-9]+/ {
            n = split($0, w, /[ \t]+/)
            tid = ""
            for (i = 1; i <= n; i++) {
                if (match(w[i], /^[0-9]+\/[0-9]+$/)) {
                    split(w[i], a, "/")
                    tid = a[2]
                    break
                }
            }
            if (tid != "") cur_tid = tid
        }
        { file = "/tmp/perf_tid" (cur_tid == "" ? "unknown" : cur_tid) ".txt"; print >> file }
    ' /tmp/perf.txt

    # List TIDs that have data, sorted numerically (smallest = oldest thread = thread1).
    tid_list=$(ls /tmp/perf_tid*.txt 2>/dev/null | sed -n 's|.*/perf_tid\([0-9]\+\)\.txt$|\1|p' | sort -n -u)
    tid_count=$(echo "$tid_list" | grep -c . || true)
    if (( tid_count > 1 )); then
        # Tab labels, SVG files, and folded data for the combined view HTML (tab 0 = All threads, then Thread 1, 2, ...).
        tab_labels=("All threads")
        tab_files=("${COMM}_flamegraph.svg")
        tab_folded_files=()
        # Folded data for "All threads" (combined) is produced from /tmp/perf.txt in perf-record-and-postprocess; we produce it here for the report.
        cat /tmp/perf.txt | stackcollapse-perf.pl 2>/dev/null | stackcollapse-recursive.pl 2>/dev/null >/tmp/perf_all.folded
        tab_folded_files+=("/tmp/perf_all.folded")
        index=1
        for tid in $tid_list; do
            file=/tmp/perf_tid${tid}.txt
            [[ -f $file ]] || continue
            thread_name=$(cat /proc/$PID/task/$tid/comm 2>/dev/null | tr -d '\n' | sed 's/[^a-zA-Z0-9._-]/_/g' | head -c 48)
            [[ -z $thread_name ]] && thread_name="untitled"
            out_name="${COMM}_thread${index}_${thread_name}_flamegraph.svg"
            folded_path="/tmp/perf_tid${tid}.folded"
            cat $file | stackcollapse-perf.pl 2>/dev/null | stackcollapse-recursive.pl 2>/dev/null | tee "$folded_path" | flamegraph.pl >"$HOME/$out_name"
            echo "    - $HOME/$out_name"
            tab_labels+=("Thread $index: $thread_name")
            tab_files+=("$out_name")
            tab_folded_files+=("$folded_path")
            (( index++ )) || true
        done
        # HTML report is generated by generate-html-report.sh (same dir).
        SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")")
        . "$SCRIPT_DIR/generate-html-report.sh"
    else
        echo "Found 0 per-thread stack, skipping per-thread flamegraph"
    fi
else
    echo "$COMM ($PID) has 1 thread, skipping per-thread flamegraph"
fi
